log:
  level: info
  production: false

plugins:
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "./accelerated-domains.china.conf.raw.txt"
        - "./apple.china.conf.raw.txt"

  - tag: "remote_forward"
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "1.1.1.1"
        - addr: "1.0.0.1"

  - tag: "local_forward"
    type: forward
    args:
      concurrent: 4
      upstreams:
        - addr: "https://223.5.5.5/dns-query"
          enable_http3: true
          enable_pipeline: true
          dial_addr: "223.5.5.5"

        - addr: "https://223.6.6.6/dns-query"
          enable_http3: true
          enable_pipeline: true
          dial_addr: "223.6.6.6"
        
        - addr: "https://1.12.12.12/dns-query"
          #enable_http3: true
          enable_pipeline: true
          dial_addr: "1.12.12.12"
        
        - addr: "https://120.53.53.53/dns-query"
          #enable_http3: true
          enable_pipeline: true
          dial_addr: "120.53.53.53"

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
        #- exec: debug_print local_forward
      - exec: $local_forward

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
        #- exec: debug_print remote_forward
      - exec: $remote_forward

  - tag: "main_sequence"
    type: sequence
    args:
      - matches: "qname $direct_domain"
        exec: goto local_sequence
      - exec: goto remote_sequence

  - type: udp_server
    args:
      entry: main_sequence
      listen: :53
